stages:
  - Style
  - StaticAnalysis
  - Build
  - Unittest
  - Release

image: shibohan/droneoa:latest

cache:
  paths:
    - ccache/

before_script:
  - apt update >/dev/null && apt install -y git >/dev/null
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

cpplint:
  stage: Style
  script:
    - pip install cpplint --quiet
    - cd ./src/droneoa_ros
    - cpplint --linelength=120 --recursive .
    - cd ..
    - cd ..

pylint:
  stage: Style
  script:
    - pip install pylint --quiet
    - cd ./src/droneoa_ros
    - find . -type f -name "*.py" | xargs pylint
    - cd ..
    - cd ..

catkinlint:
  stage: StaticAnalysis
  script:
    - apt-get install python-catkin-lint -y
    - catkin_lint -W0 .
  allow_failure: true

haros:
  stage: StaticAnalysis
  script:
    - apt-get install libmagic-dev -y
    - pip install haros
    - pip install python-magic
    - pip install ply nose
    - pip install -e git+https://github.com/timtadh/pyflwor.git#egg=pyflwor
    - pip install radon
    - apt-get install cppcheck -y
    - apt-get install cccc -y
    - apt-get install cloc -y
    - cd ./src/droneoa_ros
    - mkdir ../../../report
    - haros --config ./haros_config.yaml analyse -d ../../../report
    - cd ..
    - cd ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-static-report"
    paths:
      - ./report/
    expire_in: 1 week
  allow_failure: true

catkin_make:
  stage: Build
  script:
    - sh ./src/droneoa_ros/scripts/ci/prescript.sh
    - catkin_make
  retry: 2

catkin tools:
  stage: Build
  script:
    - sh ./src/droneoa_ros/scripts/ci/prescript.sh
    - catkin build --summarize --no-status --force-color
  retry: 2

Unittest:
  stage: Unittest
  script:
    - sh ./src/droneoa_ros/scripts/ci/prescript.sh
    - catkin_make
    - source ./devel/setup.sh
    # - roscore &
    - rosrun droneoa_ros droneoa_ros_utiltest || true
    - rosrun droneoa_ros droneoa_ros_commandtest || true
    - sh ./src/droneoa_ros/scripts/ci/checkUnittestResult.sh
  retry: 2

Release_Package:
  stage: Release
  script:
    - cd ./src/droneoa_ros
    - mkdir ../../../release
    - cp -R ./scripts/dev_setup ../../../release/dev_setup
    - cp -R ./scripts/deploy_setup ../../../release/deploy_setup
  artifacts:
    name: "$CI_COMMIT_BRANCH-release-scripts"
    paths:
      - ./release/
    expire_in: 4 weeks
  only:
    - tags
    - latest-stable
    - latest-dev
