stages:
  - cpplint
  - build
  - unittest

image: ros:melodic-ros-core

cache:
  paths:
    - ccache/

variables:
  ROS_PACKAGES_TO_INSTALL: "mavros"

before_script:
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
  - echo 'deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial main' || tee /etc/apt/sources.list.d/realsense-public.list
  - apt-key adv --keyserver keys.gnupg.net --recv-key C8B3A55A6F3EFCDE || apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-key C8B3A55A6F3EFCDE
  - add-apt-repository "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial main"
  - apt-get update -qq
  - apt-get install librealsense2-dkms --allow-unauthenticated -y
  - apt-get install librealsense2-dev --allow-unauthenticated -y
  - apt-get install ros-melodic-cv-bridge -y
  - apt-get install ros-melodic-image-transport
  - apt-get install ros-melodic-tf -y
  - apt-get install ros-melodic-diagnostic-updater -y
  - apt-get install ros-melodic-ddynamic-reconfigure -y
  - cd src
  - git clone https://github.com/IntelRealSense/realsense-ros.git
  - cd realsense-ros/
  - git checkout `git tag | sort -V | grep -P "^\d+\.\d+\.\d+" | tail -1`
  - cd ..
  - cd ..

cpplint:
  stage: cpplint
  script:
    - pip install cpplint --quiet
    - cd ./src/droneoa_ros
    - cpplint --linelength=120 ./test/*.cpp ./src/*.cpp ./include/droneoa_ros/*.hpp
    - cd ..
    - cd ..

catkin_make:
  stage: build
  script:
    - catkin_make

catkin tools:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color

Unittest:
  stage: unittest
  script:
    - catkin_make
    - source ./devel/setup.sh
    - rosrun droneoa_ros droneoa_ros_utiltest