image: ros:melodic-ros-core

cache:
  paths:
    - ccache/

variables:
  ROS_PACKAGES_TO_INSTALL: "mavros"

before_script:
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

catkin_make:
  stage: build
  script:
    - catkin_make

catkin tools:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
