stages:
  - Style
  - StaticAnalysis
  - Build
  - Unittest

image: ros:melodic-perception

cache:
  paths:
    - ccache/

variables:
  ROS_PACKAGES_TO_INSTALL: "mavros"

before_script:
  - apt-get update
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

cpplint:
  stage: Style
  script:
    - pip install cpplint --quiet
    - cd ./src/droneoa_ros
    - cpplint --linelength=120 ./test/*.cpp ./src/*.cpp ./include/droneoa_ros/*.hpp ./src/OAC/*.cpp ./include/droneoa_ros/OAC/*.hpp ./src/Utils/*.cpp ./include/droneoa_ros/Utils/*.hpp
    - cd ..
    - cd ..

catkinlint:
  stage: StaticAnalysis
  script:
    - apt-get install python-catkin-lint -y
    - catkin_lint -W0 .
  allow_failure: true

haros:
  stage: StaticAnalysis
  script:
    - pip install haros
    - pip install ply nose
    - pip install -e git+https://github.com/timtadh/pyflwor.git#egg=pyflwor
    - pip install radon
    - apt-get install cppcheck -y
    - sudo apt-get install cccc -y
    - cd ./src/droneoa_ros
    - mkdir ../../../report
    - haros --config ./haros_config.yaml analyse -d ../../../report
    - cd ..
    - cd ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-static_report"
    paths:
      - ./report/
    expire_in: 1 week
  allow_failure: true

catkin_make:
  stage: Build
  script:
    - sh ./src/droneoa_ros/scripts/ci/prescript.sh
    - catkin_make
  retry: 2

catkin tools:
  stage: Build
  script:
    - sh ./src/droneoa_ros/scripts/ci/prescript.sh
    - catkin build --summarize --no-status --force-color
  retry: 2

Unittest:
  stage: Unittest
  script:
    - sh ./src/droneoa_ros/scripts/ci/prescript.sh
    - catkin_make
    - source ./devel/setup.sh
    - rosrun droneoa_ros droneoa_ros_utiltest
  retry: 2
